local core = require('core')

eng             = { }
eng.init        = core.open
eng.done        = core.close
eng.has_table   = core.hasTable
eng.has_id      = core.hasId
eng.has_tag     = core.hasTag
eng.has_notags  = core.hasNoTags
eng.new_task    = core.newTask
eng.new_tag     = core.newTag
eng.del_task    = core.delTask
eng.del_tag     = core.delTag
eng.set_option  = core.setOption
eng.set_tag     = core.setTag
eng.clear_tag   = core.clearTag
eng.get_task    = core.getTask
eng.gettasks    = core.getTasks
eng.get_tags    = core.getTags
eng.get_options = core.getOptions
eng.upd_task    = core.updTask
eng.upd_tag     = core.updTag
eng.go_next     = core.goNext
eng.last_row    = core.lastRow
eng.Begin       = core.Begin
eng.End         = core.End
eng.isdate      = core.isDate
eng.isanytime   = core.isAnytime
eng.istomorrow  = core.isTomorrow
eng.isfuture    = core.isFuture
eng.istoday     = core.isToday
eng.isyesterday = core.isYesterday
eng.islate      = core.isLate
eng.daysmonth   = core.daysMonth
